.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/help-support.md, .github/workflows/ci_action.yml
I only set up the part of CI that is mirroring to gitlab. For running tests or linters we would have to install `eo-grow` which would mean that we need `eo-learn` `1.0` which is not released yet.
=> Basic github actions and templates

README.md
Readme looks great, here are just some minor suggestions.
=> Minor updates of readme file

MANIFEST.in, Makefile, README.md, requirements-dev.txt, requirements.txt, setup.py
Added some missing things to prepare for release.
=> Prepared for release

.gitignore, eogrow/pipelines/batch_to_eopatch.py, eogrow/pipelines/download.py, eogrow/pipelines/download_batch.py, eogrow/pipelines/merge_samples.py, eogrow/pipelines/sampling.py, eogrow/pipelines/training.py, eogrow/utils/types.py, requirements.txt, tests/test_config_files/download_and_batch/batch_to_eopatch.json, tests/test_config_files/download_and_batch/batch_to_eopatch_no_userdata.json
After the switch to pydantic models and enums in sh-py, a few schemas recieved a small update.
Build work until shpy is released, so this MR can wait a bit.
=> Update config schemas

eogrow/core/area/base.py, eogrow/core/area/batch.py, eogrow/core/area/utm.py, eogrow/utils/grid.py, tests/test_utils/test_grid.py
This part implements functionalities for creating transformations between area managers.
=> Grid switching, part 2

eogrow/core/area/batch.py
This MR switches BBox reconstruction from rounding geometries to recalculating with the given information, as suggested.
=> Better batch bbox reconstruction

.github/workflows/ci_action.yml
Notice that the target branch of this PR is intentionally master. It is because only on master branch this fix will have a desired effect (because of scheduled events).
=> Fixed branch checkouts for scheduled events in GitHub action

eogrow/pipelines/batch_to_eopatch.py, tests/test_config_files/download_and_batch/batch_to_eopatch_no_userdata.json
PR https://github.com/sentinel-hub/eo-grow/pull/60 broke the functionality of adding custom processing nodes at the end. This new parameters makes it possible to do that again.
=> Added save_early functionality to BatchToEOPatchPipeline

pyproject.toml
This enables mypy checking init arguments for correct types.
=> Add pydantic plugin to mypy

.github/workflows/ci_action.yml, setup.py
Everything with Python 3.10 now works :tada:
=> Support for Python 3.10

setup.py
The previous version of `parse_requirements` that ignored lines with `/` character was not completely correct.
=> Minor setup update

eogrow/pipelines/download.py, tests/test_config_files/download_and_batch/download_l1c_q1.json
Hotfix until this is solved properly in eo-learn
=> add temporary fix for resampling type

eogrow/core/storage.py, eogrow/pipelines/download.py, eogrow/pipelines/download_batch.py, eogrow/pipelines/features.py, eogrow/pipelines/sampling.py, eogrow/pipelines/testing.py, eogrow/pipelines/training.py, eogrow/utils/validators.py
Pydantic updated their mypy plugin in the new version.
This makes it check defaults and default factories. It actually found a few bugs! But mostly I just had to specialize default factories.
=> fix issues found by new version of pydantic

.github/workflows/ci_action.yml
Similar to https://github.com/sentinel-hub/eo-learn/pull/450
=> Improve CI triggers

eogrow/core/storage.py, eogrow/pipelines/download.py, eogrow/pipelines/download_batch.py, eogrow/pipelines/features.py, eogrow/pipelines/sampling.py, eogrow/pipelines/testing.py, eogrow/pipelines/training.py, eogrow/utils/validators.py
They released a new version with a fixed mypy plugin
=> Remove temporary pydatic fix

.github/workflows/ci_action.yml, eogrow/pipelines/export_maps.py, eogrow/utils/map.py, eogrow/utils/vector.py, tests/test_core/test_schemas.py, tests/test_utils/test_map.py
@mlubej You said that we have some bug for the cogification of uint8 right? Can you tell me how to add a test that would detect that?
=> Improve tests for eogrow.utils

eogrow/pipelines/byoc.py, requirements-dev.txt, tests/test_config_files/byoc/ingest_lulc.json, tests/test_config_files/byoc/prepare_lulc_data.json, tests/test_pipelines/test_byoc.py
It's scary to add functionality to a pipeline that is not tested properly, so I added some base tests before upgrading
=> Byoc pipeline tests

eogrow/pipelines/download.py
Change after this was fixed in eo-learn
=> properly propagate resampling parameters

eogrow/core/area/base.py, eogrow/core/area/custom_grid.py, eogrow/pipelines/testing.py, examples/basic-tutorial.ipynb, tests/test_core/test_area/test_batch.py, tests/test_core/test_area/test_custom_grid.py, tests/test_core/test_area/test_utm.py
This is likely the last of *reductive* updates to the old area manager. Mostly just to make further interface designs easier
=> Reduce area manager further

eogrow/pipelines/sampling.py, eogrow/pipelines/zipmap.py
Resolving issues that will occur after https://github.com/sentinel-hub/eo-learn/pull/522 goes to master
=> fix some type issues after new type information in eolearn.features

eogrow/core/area/__init__.py, eogrow/core/area/base.py, eogrow/core/area/batch.py, eogrow/core/area/utm.py, requirements-dev.txt, tests/test_core/test_area/test_base.py, tests/test_core/test_area/test_batch.py, tests/test_core/test_area/test_new_batch.py, tests/test_core/test_area/test_new_utm.py, tests/test_core/test_area/test_utm.py, tests/test_pipelines/test_byoc.py
1. Extracts dealing with an AOI into a `BaseSplitterAreaManager` (since it's common to both splitter based managers)
2. Implements new Batch area manager
3. adds tests for it that (with some mocking)
4. I learned some new tricks so I fixed some old tests as well before i forgot about it
=> Batch area manager rework

eogrow/core/area/base.py, eogrow/core/area/batch.py, eogrow/core/area/custom_grid.py, eogrow/core/pipeline.py, eogrow/types.py
Mostly related to docstrings.
I guess it's time to merge the big one afterwards.
=> Some minor polish

eogrow/core/area/base.py, eogrow/core/area/custom_grid.py, tests/test_core/test_area/test_base.py
Still wont support -t filtration, but it does filter the grid.
=> Move patch_list filtration to grid

eogrow/tasks/spatial.py, tests/test_tasks/test_spatial.py
=> Add tests for tasks spatial

eogrow/core/area/base.py, eogrow/core/logging.py, eogrow/core/pipeline.py, eogrow/utils/eopatch_list.py, eogrow/utils/testing.py, tests/test_core/test_area/test_base.py
There wasn't much to change, the code abstraction is good :D
=> create a naming distinction between patch_list and patch_names

examples/basic-tutorial.ipynb
Removes fields pertaining to the EOPatch manager and updates the ones with the area manager
=> Make basic tutorial reflect area manager changes

eogrow/utils/testing.py, tests/conftest.py, tests/test_config_files/byoc/prepare_lulc_data.json, tests/test_config_files/split_grid/split_batch.json, tests/test_config_files/split_grid/split_utm.json, tests/test_pipelines/test_batch_to_eopatch.py, tests/test_pipelines/test_byoc.py, tests/test_pipelines/test_download.py, tests/test_pipelines/test_export_maps.py, tests/test_pipelines/test_features.py, tests/test_pipelines/test_import_vector.py, tests/test_pipelines/test_merge_samples.py, tests/test_pipelines/test_prediction.py, tests/test_pipelines/test_sampling.py, tests/test_pipelines/test_split_grid.py, tests/test_pipelines/test_testing.py, tests/test_pipelines/test_zipmap.py
Not all cases are ported ATM as agreed.
=> Separate pipeline dummy data generation from execution/testing

tests/test_pipelines/test_import_tiff.py, tests/test_pipelines/test_training.py
Rasterization pipeline was left to @mlubej
=> Port rest of pipeline tests

eogrow/core/logging.py, pyproject.toml
Adds timestamps and color to stdout logs
I intentionally skipped the date so that it doesn't clutter the output
=> Add time to stdlogs

.github/workflows/ci_action.yml, .github/workflows/scheduler_caller.yml
More info in https://github.com/sentinel-hub/eo-learn/pull/662
=> Split github actions per trigger and make use of reusable workflows

eogrow/cli.py
We most use `tmux`, and the `--stop` flag only worked sometimes (dangerous)
=> Remove `screen` and `stop` CLI flags

eogrow/utils/testing.py
Before we do any work on the testing utils I decided to do some refactoring.
I removed the unnecessary class (there was nothing class-like about it).
This will also make it easier to add custom tailoring to `compare_content` etc.
=> Refactor testing utils

eogrow/utils/testing.py
Always great to find another issue the same day you release a patch version
=> Add flag for testing logs in content comparison

CHANGELOG.md, eogrow/__init__.py, eogrow/pipelines/download.py, eogrow/pipelines/download_batch.py
the eo-grow had a bug that was not detected by mypy???
=> fix bug and extract method for getting evalscripts

eogrow/pipelines/batch_to_eopatch.py, eogrow/pipelines/export_maps.py, eogrow/pipelines/import_tiff.py, tests/pipelines/test_import_tiff.py, tests/test_config_files/import_tiff/import_tiff_timeless.json
We can either merge it now or wait for the new version (the only reason to wait is the VSI not being enabled but that would only matter if someone would run stuff on develop this week)
=> Patch for new eo learn version

eogrow/core/pipeline.py, eogrow/core/schemas.py
Willing to take suggestions for names
=> Switch from ray worker types to a full resource request specification

eogrow/core/logging.py, eogrow/core/pipeline.py
This let's us use the methods in other parts as well.
Tried to keep it simple.
=> Make logging a tiny bit more customizable

.pre-commit-config.yaml, eogrow/core/area/base.py, eogrow/pipelines/sampling.py, eogrow/pipelines/testing.py, pyproject.toml
Updates the pre-commit and ruff a bit
=> Minor revisions

eogrow/utils/testing.py
I didn't see any other stats calculation methods being tested, so I wasn't sure what to do. This will be tested in downstream applications, but still, not perfect..
The implementation with the try/except is not the best.. let me know if you'd prefer an alternative approach
=> Add pandas parquet loader and update vector stats comparison

docs/source/conf.py, docs/source/examples.rst, docs/source/index.rst, examples/lets-build-a-model.ipynb
https://eo-grow.readthedocs.io/en/add-examples-to-docs/examples/lets-build-a-model.html
=> Add examples to docs

README.md
Acknowledgements to Smart Farm and Agri-environmental Big Data Space project.
=> Acknowledgements 

eogrow/pipelines/download_batch.py, eogrow/tasks/common.py
Went with a very simple approach to it.
=> Retry 3 times if batch dowload monitoring returns 404

.pre-commit-config.yaml, CHANGELOG.md, eogrow/__init__.py, eogrow/pipelines/download_batch.py, eogrow/utils/map.py, eogrow/utils/pipeline_chain.py
won't pass until #356 is merged
=> Prepare release 1.7.13

.github/workflows/ci_action.yml, tests/test_config_files/export_maps/export_maps_data.json, tests/test_config_files/export_maps/export_maps_mask.json, tests/test_config_files/export_maps/export_maps_mask_local_copy.json, tests/test_configs.py
Changes:
- add config validation tests
- fix configs
=> Add config validation tests
