sentinel-hub/eo-grow

eogrow/pipelines/features.py
The pipeline now has an option for specifying the output dtype to allow reducing of memory needed for the data.
Despite the recent improvements to `MergeEOPatchTask` it causes some noticeable memory spikes due to data copying. For this reason parts of the pipeline have been linearized by hand (since it does not change the functionality) to deliver a less volatile memory consumption.
=> Improve memory usage in features pipeline

.github/workflows/ci_action.yml, eogrow/core/config.py, eogrow/core/eopatch.py, eogrow/pipelines/merge_samples.py, eogrow/tasks/features.py, eogrow/utils/testing.py, pyproject.toml, requirements-dev.txt
While using `mypy` in `eo-grow` is severely crippled by lack of types in `sh-py` and `eo-learn`, it would be shameful to not use it, since the code is 100% annotated.
I read up on how to install type stubs for packages, and there is the option of `mypy --install-types --no-interaction eogrow` the developers suggest that the best option is to install the via explicit mentions in the requirements file, so that versions can be fixed if needed. Using the above command also requires the type-checking to happen twice (the first one collects information on which stubs to install).
=> Add mypy action

eogrow/core/area/batch.py, eogrow/core/eopatch.py, eogrow/core/logging.py, requirements.txt
This PR is a consequence of https://github.com/sentinel-hub/sentinelhub-py/pull/250 and should be merge only after `sentinelhub-py` `3.5.0` is released.
=> Updates for sentinelhub-py version 3.5.0

eogrow/pipelines/batch_to_eopatch.py, requirements-dev.txt, tests/test_pipelines/test_batch_to_eopatch.py
A continuation of https://github.com/sentinel-hub/eo-grow/pull/29. This PR makes sure that even if `userdata.json` doesn't exist the pipeline succeeds if parameters for handling userdata are not defined.
=> Handling case when userdata.json doesn't exist

eogrow/pipelines/training.py, eogrow/utils/filter.py, tests/test_config_files/training/lgbm_training_label_filter.json, tests/test_config_files/training/lgbm_training_no_filter.json
We usually left references in shape of `(n_samples, 1)`, so I added `ravel` to preprocessing so that functions no longer complain.
=> Add seeds to tests for training pipelines, reduce amount of warnings

eogrow/core/pipeline.py, eogrow/pipelines/batch_to_eopatch.py, eogrow/pipelines/download.py, eogrow/pipelines/features.py, eogrow/pipelines/prediction.py, eogrow/pipelines/rasterize.py, eogrow/pipelines/sampling.py, eogrow/utils/filter.py, tests/test_utils/test_filter.py
Running `BatchToEOPatchPipeline` on 300K patches showed some flaws of "skip existing" functionality. This PR makes basic improvements:
- adds more logs and a progress bar to the filtering procedure,
- renames the filtering function because the previous name `get_patches_without_all_feature` could be interpreted as "get patches that has none of the give features".
- fixes a bug in providing output features in `BatchToEOPatchPipeline` where skipping existing didn't work if EOPatches didn't have timestamps.
A large problem remains - filtering EOPatches is still too slow if we parallelize it only over threads. We could parallelize it also over the cluster. For this I suggest implementing a bit more general parallelization utilities that can be used here. That can be done in future work.
=> Improved "skip existing" functionality and a fix for using it in BatchToEOPatchPipeline.

requirements-dev.txt, requirements.txt
A while ago we had to restrict `responses` since it was breaking our tests. It looks like it can be removed now. We also need to bump the version of `eo-learn` because our pipelines use a feature that was added in the new version.
=> Update version restrictions

.github/workflows/ci_action.yml, eogrow/core/area/custom_grid.py
Does two things:
1. reenables `chain` test, since `eolearn` got updated
2. mutes the `CustomGridAreaManager` type issue so that we don't overlook other issues due to a known failure
=> Patch tests until AreaManager fix

eogrow/cli.py, eogrow/core/area/batch.py, eogrow/core/eopatch.py, eogrow/core/logging.py, eogrow/core/storage.py, eogrow/pipelines/batch_to_eopatch.py, eogrow/pipelines/download.py, eogrow/pipelines/download_batch.py, eogrow/pipelines/sampling.py, eogrow/pipelines/training.py, eogrow/utils/testing.py, eogrow/utils/vector.py
Changes:
- added support for `maxcc` and `other_params` in batch pipeline,
- replaced `tile_buffer` with `tile_buffer_x` and `tile_buffer_y` in batch area manager,
- separated input data parameters into a sub-schema in batch pipeline and therefore allowing potential data fusion use cases,
- fixed various spelling mistakes in the package.
2nd and 3rd change on the list are code/config breaking but I think they are worth doing now while we still don't have that many use cases.
=> A few batch pipeline improvements

eogrow/core/logging.py, eogrow/pipelines/prediction.py, eogrow/utils/export.py, eogrow/utils/fs.py, eogrow/utils/testing.py, tests/test_utils/test_fs.py
All these changes were done for a use case of having a prediction pipeline that is using a Tensorflow model.
- Parameter `model_filename` was moved from `BasePredictionPipeline` to its 2 child classes. That is because a Tensorflow model consists of a folder structure with multiple files and it is nicer to handle its name a bit differently.
- Implemented `LocalFolder` utility, improved the overall implementation of `LocalFile`/`LocalFolder`, and added more unit tests.
- Improvements in logs:
* Figured out how to explicitly prevent the crashes because of emitting logs within emitting logs - by adding a default filter `FilesystemFilter` to the `FilesystemHandler`.
* Fixed minor issues with config parameters.
=> LocalFolder and improvements in logging and prediction pipelines

eogrow/core/area/custom_grid.py, eogrow/core/pipeline.py, eogrow/pipelines/batch_to_eopatch.py, eogrow/pipelines/download.py, eogrow/pipelines/prediction.py, eogrow/pipelines/rasterize.py, eogrow/pipelines/sampling.py, eogrow/pipelines/switch_grids.py, eogrow/pipelines/testing.py, eogrow/tasks/prediction.py, eogrow/utils/enum.py, eogrow/utils/meta.py, eogrow/utils/testing.py, eogrow/utils/validators.py
When updating another project I remembered that `ŧype: ignore` has an option to specify precisely the type of error you're ignoring. Since this is much better than just ignoring all errors in a line, I re-did all such comments.
In some cases I also manged to avoid the issue by adjusting something else, reducing the number of ignore comments from 20 to 14 :tada:
=> specialize all type: ignore comments and get rid of some

eogrow/utils/fs.py, tests/test_utils/test_fs.py
Added 2 improvements that were inspired by FD use case:
- Let's say that a local object is opened with write mode, nothing is written in it, and either an error happens or it is just closed. In the previous version an additional error would be raised which was very confusing. In the new version it doesn't do anything which is much more natural behavior.
- A local object is always created in a folder with a unique name. This folder can have suffix that helps users to identify what is in the folder. In this improvement the suffix is constructed with local object class name and a name of the item contained inside.
=> LocalObject improvements

eogrow/utils/meta.py, tests/test_utils/test_meta.py
I noticed `get_package_versions` was using wrong package name and therefore failing. I fixed this and added more unit tests which now cover all functions in `eogrow.utils.meta` module.
=> Fixed get_package_versions and added more unit tests

eogrow/pipelines/rasterize.py
Minimal changes that allow rasterizing temporal vector features. If this is merged, then the pipeline can be extended with only the `build_pipeline` method overridden in order to first load existing patches (to have timestamps), and then temporarily add (temporal) vector features that are rasterised.
=> Allows rasterization of temporal/timeless vector features.

eogrow/utils/fs.py
Otherwise `LocalFile` used in `with` has the `BaseLocalObject` type
=> Improve signatures for local objects

eogrow/core/eopatch.py, eogrow/utils/general.py, tests/test_utils/test_fs.py, tests/test_utils/test_general.py
A couple of minor improvements I prepared the other day while working on FD use case:
- In case given patch ids are not found now a more informative error is raised. I added even a function that prepares a nicer repr for large lists.
- Added a few extra checks into tests for local objects because there were some doubts if perhaps a local copy doesn't get deleted at the end. These checks make sure it does.
=> Minor improvements

eogrow/core/schemas.py, eogrow/pipelines/download_batch.py, eogrow/pipelines/export_maps.py, eogrow/pipelines/merge_samples.py, eogrow/pipelines/switch_grids.py, eogrow/pipelines/training.py
Some pipelines do not support certain options, such as setting a custom patch list. This makes sure that faulty configurations are rejected at validation time. 
By extension this solves issues with use of -t flag
=> Fix parameters for pipelines that do not support them

eogrow/pipelines/batch_to_eopatch.py
As noticed by @batic the filtration currently does not work correctly, because the filtration function cannot figure out which meta info features are present, and therefore if a meta info feature is part of the output, all the patches are marked as incomplete.
This fix shifts the 'wrongness' to the other side. If the meta-feature is not present, but some others are (so a `metainfo.json` exists), it mark this requirement as passing. This shouldn't be too error prone, since all other features must be present as well, and it is unlikely that such a scenario is encountered.
Better fixes can be done once we figure out how to handle meta-info features in general.
=> Remove meta info name when filtering Batch2EOPatch

eogrow/core/logging.py, eogrow/core/pipeline.py, eogrow/core/schemas.py, eogrow/utils/testing.py
Changes:
- Logging filters now don't automatically accept all logs with level e.g. info or warning above.
- I noticed that we actually don't need `LoggingManagerSchema` because we can access the same parameters in a different way in base `Pipeline` class. This way we can move these logging parameters back to `LoggingManager` which makes them more organized and ready for future improvements.
=> Minor logging updates

eogrow/core/base.py, eogrow/core/schemas.py, eogrow/pipelines/batch_to_eopatch.py, eogrow/pipelines/download.py, eogrow/pipelines/features.py, eogrow/pipelines/prediction.py, eogrow/pipelines/rasterize.py, eogrow/pipelines/testing.py, eogrow/tasks/prediction.py, eogrow/utils/validators.py, tests/test_core/test_schemas.py, tests/test_pipelines/test_batch_to_eopatch.py
1. Allow custom types in schemas. It does not change validation of the previous allowed types at all, but for any other types it adds an `isinstance` validation. If a schema has such a type, then open-api templates do not work, but minimal templates dont care.
2. Pipelines now parse dtypes at validation
=> Properly parse dtypes at validation

eogrow/pipelines/export_maps.py, eogrow/utils/map.py
In the ExportMapPipeline the tiff exporting task correctly exports the dtype and the no_data part of the EOPatches, but this information doesn't get passed on when the separate tiffs get merged using `gdal_merge.py` and later on in the cogification part.
This MR:
- passes on the `dtype` and the `nodata` value from the pipeline config to the `_merge_map_function`
- converts the python-based `dtype` string to the GDAL-specific combo (workaround for missing 8-bit tiffs)
- passes the `dtype` and `nodata` wherever they can be accepted (`gdal_merge.py` and `gdal_translate`)
- improves the `gdal_merge.py` subprocess string
=> ExportMapPipeline ignores dtype and nodata when merging

eogrow/core/storage.py, eogrow/utils/general.py, tests/test_config_files/other/aws_storage_test.json, tests/test_core/test_storage.py, tests/test_utils/test_general.py
This PR changes that in case given AWS profile doesn't exist a warning is shown instead of an error. It also adds a test that checks this.
The reason for this is purely practical - if you run a pipeline on AWS instance with a role that already allows accessing S3 buckets you don't need AWS profiles. But if you run a pipeline locally then you need to specify `aws_profile` in order to access S3 buckets. So to avoid constantly changing `aws_profile` parameter it seems easier to just give a warning instead of an error. Although I'm not 100% sure if this really justifies this change. :thinking:
=> Handling of nonexistent aws_profile

.gitignore, docs/Makefile, docs/source/conf.py, setup.py
Same things as in sentinelhub-py, except that here we don't yet need `custom_reference` folder.
=> A few docs-related improvements

eogrow/pipelines/download.py, eogrow/pipelines/rasterize.py, eogrow/pipelines/sampling.py, eogrow/utils/validators.py, tests/test_config_files/rasterize/rasterize_pipeline.json
Exposes another parameter of the rasterization task.
I also noticed a common pattern of validators, which i managed to extract into `ensure_exactly_one_defined` function. It was tested locally.
=> Add raster_shape param to rasterize pipeline

eogrow/pipelines/download.py, eogrow/pipelines/download_batch.py, eogrow/utils/validators.py, tests/test_config_files/download_and_batch/download_season.json, tests/test_utils/test_validators.py
Previously data collections were specified by a string, which was either a name of an existing collection, or used as a byoc/batch ID. This caused issues when using custom collections, and using BYOC collections without evalscripts was difficult (couldn't specify bands). Also default values of such fields had to be strings, and when working in python (notebooks) one couldn't just pass in a collection.
Now one can:
- provide a `DataCollection` (for direct python work and defaults).
- provide a name of an existing collection
- provide a (prefixed) ID of a BYOC/BATCH collection for basic definition
- provide a detailed definition via `DataCollectionSchema` (which supports BYOC/BATCH automation via prefixes)
=> Better DataCollection parsing

docs/source/conf.py, eogrow/pipelines/download_batch.py, eogrow/utils/validators.py, requirements-docs.txt
By leveraging `autodoc_pydantic` we now build far more understandable docs of Schema, which include validators/parsers and field descriptions
=> Improve Schema docbuilding

eogrow/pipelines/byoc.py, eogrow/pipelines/export_maps.py, eogrow/pipelines/ingest_byoc.py, eogrow/utils/map.py, eogrow/utils/validators.py, tests/test_config_files/export_maps/export_maps_mask.json, tests/test_stats/export_maps/export_maps_data.json, tests/test_stats/export_maps/export_maps_mask.json, tests/test_utils/test_validators.py
1. Changes output of `ExportMapsPipeline` to save each map to its own subfolder (instead of using a prefix), which makes it easier to ingest them as BYOC collections. Name is now also optional (feature name is used if not provided). Tests are updated.
2. Add generic validator for checking that two parameters are defined at the same time. Tests are updated.
3. Add a pipeline that accepts the output of an `ExportMapsPipeline` and ingests the tiffs as a BYOC collection. No tests yet.
=> Pipeline for ingesting BYOC collections

docs/source/conf.py, requirements-docs.txt
Same solution as for `sentinelhub-py` in https://github.com/sentinel-hub/sentinelhub-py/pull/316
You can check the newly built docs [here](https://eo-grow.readthedocs.io/en/docs-github-url/).
=> Fixed GitHub URL links in documentation

eogrow/utils/map.py
ExportToTiff pipeline didn't behave as expected. When merging tiffs, I wanted to set the empty space to the no-data value, turns out there were issues because of:
- not setting the `-init` param
- not using the values as strings (- was understood as a parameter???)
Thanks @batic for the help.
=> Fix setting of nodata in export2tiff pipeline, round 2

eogrow/pipelines/export_maps.py, eogrow/utils/map.py
I tried adding support for temporal byocs, but the pipeline itself was a bit hard to read. So as a first step I'd like to reorganize it a bit. Should make later changes easier to follow.
Seems like github butchered the diffs a bit... Its mostly reordering and extracting to methods.
=> Refactor ExportMap pipeline to allow easier changes in future

eogrow/pipelines/export_maps.py, eogrow/utils/map.py, tests/test_utils/test_map.py
Silences output of gdal calls in favor of tqdm, making logs much more readable.
In the logs there was a constant warning:
```
Warning 1: General options of gdal_translate make the COPY_SRC_OVERVIEWS creation option ineffective as they hide the overviews
```
I have removed this option in this MR, but it should be investigated if that is really the way to go. Link to [cogification docs](https://gdal.org/drivers/raster/cog.html#raster-cog)
=> Make export pipeline logs more readable

eogrow/pipelines/export_maps.py, eogrow/utils/map.py, tests/test_config_files/export_maps/export_maps_data.json, tests/test_utils/test_map.py
By switching from `gdal_merge` to `gdalwarp` we can now specify how to resample tiffs that are warped. This is a possible improvement for pixel misalignment.
Another benefit is that `gdal_merge` loads all files into memory while `gdalwarp` runs much more memory-conservative.
=> Add warp resampling when merging tiffs.

eogrow/pipelines/export_maps.py, eogrow/utils/map.py
1. Removes disk-space issue that occurs due to `extract_bands` utility function not cleaning up after copying. The copying was deemed not necessary, since the utility function doesn't get used in-place (and if it does the user should take care of copying)
2. Local eo-patch tiffs are removed ASAP to preserve disk space
3. Tiffs are exported with compression. Makes the pipeline a bit slower, but saves on space (50% reduction in file-size). The names are also no longer unique-per-run, so subsequent runs override the previous ones (if the previous pipeline failed), reducing the clutter on storage when debugging.
=> Improvements for ExportToTiff pipeline

eogrow/core/eopatch.py, tests/test_core/test_eopatch.py
The eopatch manager does some shady stuff when the area uses multiple CRS.
Geopandas started complaining in 0.12, so this is a quick fix (with a test) that this should no longer be an issue.
=> Update after geopandas 0.12 changes

eogrow/pipelines/export_maps.py, eogrow/utils/map.py, tests/test_config_files/export_maps/export_maps_data_compressed.json, tests/test_config_files/export_maps/export_maps_mask.json, tests/test_config_files/export_maps/export_maps_mask_local_copy.json
This MR flips the approach of export maps from
1. export
2. merge
3. split temporally
4. cogify
The above approach could only parallelize steps 1 and 4, and we this is `eo-grow` not `eo-die-on-upscaling`, so I switched the order to:
1. export
2. split temporally
3. merge
4. cogify
All steps are now parallelizable (on the head node only so far :/, but that is a x16 speedup for m5.4xlarge).
One of the issues that prevents a very clean parallelization is that in step 2. the jobs need to be grouped input-wise (to avoid possibility of IO blocks) while steps 3 and 4 only make sense if parallel over the temporal axis.
Also due to heavy use of filesystem, a fair amount of refactoring was required to make the methods themselves parallelizable.
=> Parallelize export maps

eogrow/cli.py, eogrow/core/schemas.py, tests/test_core/test_schemas.py
Less code means less things to go wrong
Also renamed `build_minimal_template` to `build_schema_template` (the name of the old template builder) since it is now THE template, and not the minimal version of it.
=> Remove old approach to template building as it was never used

eogrow/core/storage.py
Improved the docstrings just a bit, but the main part was the removal of `show_folder_structure`.
This was useful in LCMS when the storage structure was very complex. I don't remember using this or seeing anyone use this since eogrow 1.0 was released (hence requesting @mlubej for his opinion).
=> quick cleanup of storage manager

tests/test_config_files/global_config.json, tests/test_config_files/mapping/mapping_pred.json, tests/test_config_files/prediction/prediction.json, tests/test_pipelines/test_batch_to_eopatch.py, tests/test_pipelines/test_download.py, tests/test_pipelines/test_export_maps.py, tests/test_pipelines/test_features.py, tests/test_pipelines/test_mapping.py, tests/test_pipelines/test_merge_samples.py, tests/test_pipelines/test_prediction.py, tests/test_pipelines/test_sampling.py, tests/test_pipelines/test_testing.py, tests/test_pipelines/test_training.py
reduces code duplication and makes it more obvious which cases are in the chain without additional names
=> Reorganize test marks

eogrow/pipelines/export_maps.py, tests/test_config_files/export_maps/export_maps_data.json
After debating on how this is an edge-case and wont happen, we had it happen not even a week later.
For instance, if our time spans multiple years, we could have eopatches saved in a per-year to reduce memory consumption. But then we cant use two clusters, one for exporting 2020 and one for 2021, because the maps have the same name, and the exported tiffs will override eachother (since only the map name matters).
For that edge-case the user can now provide a suffix.
=> Add option of suffix for temporary files in ExportMapsPipeline

eogrow/core/eopatch.py, tests/test_core/test_eopatch.py
It is already checked one way (batch eopatch can only be used with batch area) but it often happens that one uses batch area but not batch eopatch manager. The code fails at the end of the batch download (kinda shitty).
This is a temporary hack that checks the compatibility until eopatch and area managers are reworked.
=> Check compatibility of area/eopatch managers for Batch

.github/workflows/ci_action.yml, README.md, requirements-dev.txt
Should help us identify weak spots in tests, although it cannot follow tests in deep into eo-learn (so we can't see if we covered all edge-case configurations of a pipeline)
=> Enable codecov upload

eogrow/core/area/__init__.py, eogrow/core/area/base.py, eogrow/core/area/custom_grid.py, tests/test_core/test_area/test_custom_grid.py
In order to keep chunks smaller, i'll add them in such small updated.
For now I focused on supporting the bare minimum, and things will only be added if there is no better way of doing it.
I decided to transition grids from lists to dictionaries, because it is now impossible to have two grid files for the same CRS.
the biggest issue I have is how to name the column with eopatch names in the grid representation. I was considering just fixing it to `eopatch_name` so that the rest of the code does not need to use `self.area_manager.NAMES_COLUMN`
=> Define new BaseAreaManager and create custom grid version of it

eogrow/core/area/base.py, eogrow/core/logging.py, eogrow/utils/eopatch_list.py, tests/test_config_files/other/local_storage_test.json, tests/test_core/test_area/test_base.py
adds patch list functionality as part of the area manager
area managers can now output named bboxes, which is what eopatch managers used to do. Feels crazy that it seems to only be 20 LOC, maybe i'm overlooking something or it shows that the reowork uses a much better abstraction
=> Add eopatch manager functionality to area manager

eogrow/core/area/batch.py, eogrow/pipelines/download_batch.py
Tiles are only available AFTER analysis is done.
I moved the forced caching to a later point and added pre-analysis statuses to cause an error, so that such issues are detected.
=> Correct batch grid caching in download pipeline

eogrow/cli.py, eogrow/core/config.py, eogrow/utils/map.py, eogrow/utils/meta.py
Issue was mostly in error strings, where I believe \` makes more sense than reqular quotes anyways. In other cases it's constructing subprocess commands and shouldn't be changed
=> update files according to new changes where applicable

eogrow/utils/eopatch_list.py, eogrow/utils/ray.py, eogrow/utils/testing.py, eogrow/utils/validators.py, tests/test_tasks/test_testing.py
1. fixed testing util to not need any method
2. fixed tests for testing tasks so that they dont care if eolearn is 1.3.1 or 1.4
3. fixed some deprecation errors by correcting paths
=> Fix tests to avoid get_features method

eogrow/core/storage.py, eogrow/pipelines/byoc.py, eogrow/pipelines/download_batch.py, eogrow/pipelines/export_maps.py, eogrow/types.py, tests/test_core/test_storage.py, tests/test_pipelines/test_byoc.py
This PR addresses the following:
* removes AWS specific ACLs
* adds option to add "any FS kwargs" to storage manager
* renames the method `is_on_aws` to `is_on_s3`, which is more appropriate
* removes passing acl option to local fs; now adding non-appropriate kwargs to fs will fail (as it should)
With this changes, accessing eo-patches on non AWS S3 buckets is possible (e.g. creodias).
=> Updates needed for storing eo-patches on non AWS s3 buckets.

eogrow/core/area/base.py, eogrow/core/area/batch.py, eogrow/core/area/utm.py, tests/test_config_files/global_config.json, tests/test_config_files/split_grid/dummy_data_batch.json, tests/test_config_files/split_grid/dummy_data_utm.json, tests/test_config_files/split_grid/split_batch.json, tests/test_config_files/split_grid/split_utm.json, tests/test_core/test_area/test_base.py, tests/test_core/test_area/test_batch.py, tests/test_core/test_area/test_utm.py, tests/test_utils/test_validators.py
This resolves the area grid cache issue where these parameters were not included in the name.
This MR removes AOI modification, since the user can (and probably should) do it beforehand.
By using a parser-validator I'm able to transfer over data from old-style area configs into the new format. The user gets a deprecation warning. This will give users a bit of time to adapt :)
I am not entirely happy with the `aoi_filename` name, so any suggestions are welcome.
The fact that none of the tests notice a difference just goes to show that it was not very important.
=> Remove aoi modification in area managers

eogrow/core/storage.py
Doing this now will let us use both develop branches locally. We can also release eo-grow before sh-py if we feel like it.
=> Adapt storage for config changes in shpy 3.9.0

eogrow/utils/validators.py
`FeatureParser` was extended in the past to allow for callables, but this wasn't reflected in eo-grow validators.
Used the `FeatureParser` from eo-learn directly in the validator.
=> Extend feature validator restrict_types to allow callables

eogrow/utils/testing.py, tests/test_pipelines/test_batch_to_eopatch.py, tests/test_pipelines/test_download.py, tests/test_pipelines/test_export_maps.py, tests/test_pipelines/test_features.py, tests/test_pipelines/test_import_tiff.py, tests/test_pipelines/test_import_vector.py, tests/test_pipelines/test_merge_samples.py, tests/test_pipelines/test_prediction.py, tests/test_pipelines/test_sampling.py, tests/test_pipelines/test_split_grid.py, tests/test_pipelines/test_testing.py, tests/test_pipelines/test_zipmap.py
Compare content should be more explicit about the fact that it wants a folder.
And `run_config` can output the final folder path.
This should make it easier for more exotic test setups.
=> Adjust compare content signature

eogrow/pipelines/rasterize.py, tests/test_config_files/rasterize/base_rasterize_pipeline.json, tests/test_config_files/rasterize/base_rasterize_pipeline_features.json, tests/test_config_files/rasterize/base_rasterize_pipeline_float.json, tests/test_config_files/rasterize/rasterize_pipeline.json, tests/test_config_files/rasterize/rasterize_pipeline_features.json, tests/test_config_files/rasterize/rasterize_pipeline_float.json, tests/test_pipelines/test_rasterize.py
Changes:
- reduce scope of the pipeline to one rasterized output per config
- add validation for vector and raster features
- simplify code according to the changes
- update configs to reflect the changes (split into config chains)
- update tests according to the changes here and in https://github.com/sentinel-hub/eo-grow/pull/210 and https://github.com/sentinel-hub/eo-grow/pull/213
=> Refactor RasterizePipeline and tests

eogrow/core/logging.py, tests/test_core/test_logging.py
This is mostly relevant for configuring which packages should get through to `stdout`. For example, if you had a new package which relies on `eo-grow`, you had to copy all the defaults and add the name of your package, or your custom pipelines didn't log to stdout. But now you can just set the value to `["...", "mypackage"]`. And if a package is clouding your logs you can do something similar.
It's more of a neat workaround, because I do not feel like overhauling the logging manager ATM
=> A way to reference defaults in logging configs

eogrow/pipelines/batch_to_eopatch.py, eogrow/pipelines/prediction.py, eogrow/pipelines/rasterize.py, eogrow/pipelines/sampling.py, eogrow/utils/validators.py
Root validators make sense and are great, BUT they leave the docs messy.
Now the user needs to be careful of the order of parameters, but the docs are much nicer.
Before, each field was marked as having a validator (since there was a root validator)
Now only one of the relevant fields is marked. The validator also has a custom name (cause i felt like being extra today).
=> Switch to field validators from root validators

eogrow/core/pipeline.py, eogrow/core/schemas.py, tests/test_config_files/download_and_batch/download_dem.json, tests/test_config_files/other/simple_config.json
So things i'm not sure about:
- should it be `custom_name`, just `name`, maybe `custom_log_name`?
- do we have this parameter as a regular pipeline parameter, or as part of the `logging` config?
=> Add option for users to specify a custom name for each pipeline

eogrow/cli.py, pyproject.toml
First thing i noticed is that after we removed the encoding the `eogrow` command was borked, because the variable stayed in the method. So i removed that.
Than i asked myself a simple question. Why in the everloving "#/& is there a class here? So I removed the useless class wrapper.
I also renamed `config_filename` to `config_path` since it fits better.
=> Clean the CLI file

docs/source/common-configuration-patterns.md, docs/source/common-design-patterns.md, docs/source/config-language.md, docs/source/index.rst
I know i made a lot of typos, you know i made a lot of typos.
Let's avoid the back and forth in the review, just push a commit to the appropriate branch. You can voice any other concerns here or ping me directly.
Relevant [docs](https://eo-grow.readthedocs.io/en/add-tips-and-tricks-docs/common-configuration-patterns.html)
We should add tips and tricks for working in Jupyter as well (separate MR to limit the scope).
=> Add common configuration patterns to documentation

eogrow/utils/validators.py, tests/test_utils/test_validators.py
Changes:
- added validator for checking folder key presence
- added test
Comments:
- folder keys can be optional (sometimes defaults to "input_data")
- "input_data" key was manually added to be OK (usually not present in the structure, since it's a default)
- not sure if there is a better way. One could use `PRESET_FOLDERS` from the storage manager, but was afraid of creating circular imports
- storage structure presence is not checked in the validator, since this should already be covered
If this addition makes sense, I can then then open a new MR where this validator is applied where it makes sense
=> Validate folder key presence in storage structure

eogrow/pipelines/batch_to_eopatch.py, eogrow/pipelines/byoc.py, eogrow/pipelines/download.py, eogrow/pipelines/download_batch.py, eogrow/pipelines/export_maps.py, eogrow/pipelines/features.py, eogrow/pipelines/import_tiff.py, eogrow/pipelines/import_vector.py, eogrow/pipelines/merge_samples.py, eogrow/pipelines/prediction.py, eogrow/pipelines/rasterize.py, eogrow/pipelines/sampling.py, eogrow/pipelines/split_grid.py, eogrow/pipelines/testing.py, eogrow/pipelines/training.py, eogrow/pipelines/zipmap.py
Sadly cant be used in nested schemas or in area managers at the moment
=> Add storage key validators to pipelines

eogrow/cli.py, eogrow/core/logging.py
We decided for a simple procedure:
1. `eogrow-ray` transfers `cluster.yaml` onto the head instance (similar to configs). This does not need to be named in a 'execution-specific-way' because if you switch to a different cluster configuration you'll (almost surely) also switch the head node
2. Each pipeline checks if there is a `cluster.yaml` in the expected location, if there is, it copies it over.
Tested it out on a simple case to make sure it works
=> Store cluster.yaml in logs

eogrow/pipelines/batch_to_eopatch.py
When overriding this method it is likely the `self` is required.
=> Make method for overriding non-static

eogrow/core/storage.py, eogrow/pipelines/download.py, eogrow/pipelines/features.py, eogrow/pipelines/import_tiff.py, eogrow/pipelines/import_vector.py, eogrow/pipelines/prediction.py, eogrow/pipelines/rasterize.py, eogrow/pipelines/sampling.py, eogrow/pipelines/split_grid.py, eogrow/pipelines/testing.py, eogrow/pipelines/zipmap.py
I am unsure about the parameter name. I was also considering the `use_zarr` flag, but i'm worried that this flag would be used in some pipelines to also use zarr optimizations.
Open to suggestions.
The tests do not include this, since Zarr is not a requirement of eo-grow. I turned this flag on in the global config and the whole thing worked automagically.
=> Add a flag to use zarr arrays

eogrow/core/area/base.py
This took a bit of experimenting but the end result is that in a grid of 2 x 100 000 patches, the time to generate the patch list goes from 18s to 1.75s :smile_cat: 
The idea was to stay in geopandas as long as possible. Some other things I tried:
- Mapping directly on `grid.geometry` kinda works, but since `BBox` is not a valid geometry, an error gets raised (and silenced), but in the process of raising this error a deprecation warning for the BBox string representation pops up :see_no_evil:. I mean we could silence that, but it also only gets us to 2.7s
- Then i tried applying a helper function directly onto the `grid.bounds`. This got me to 2.1s, but the code was long and the helper function couldn't be a lambda (does not capture the crs), so it was an additional definition which had …
=> Make patch_list generating faster

.github/workflows/ci_action.yml, .github/workflows/ci_trigger.yml, .gitlab-ci.yml
Changes:
- mirror tags as well
- trigger on releases also (should trigger internal docker build)
=> Enable Github actions to trigger internal Gitlab CI

eogrow/cli.py, tests/test_cli.py, tests/test_config_files/chain_pipeline_to_validate.json
As per usual, one finds the bug just after release :upside_down_face: 
The problem is that variables are handled with `interpret_config_from_dict` which pops them directly from the config. In this case the config is `{"pipeline_config": ...}` and thus does not have variables (which are one level lower). The interpretation then fails because it finds variables that it does not have defined (because it didnt manage to pop the correct variable dict). Tried to get around that.
Do you think this is important enough to release 1.7.1 tomorrow?
=> Fix pipeline-chain validation

eogrow/core/pipeline.py, eogrow/core/schemas.py, tests/core/test_pipeline.py
Open to any naming changes...
The error is raised at the very end, so that logs and reports are finalised beforehand
=> Add option for pipeline to fail with exception

eogrow/core/pipeline.py, tests/core/test_pipeline.py
The `finally` clause kicks in even if another exception is raised in the `except` clause
any improvement suggestions are welcome
=> Store exception traceback in logs f pipeline fails

eogrow/utils/testing.py, tests/test_stats/import_vector/import_vector.json, tests/test_stats/import_vector/import_vector_temporal.json, tests/test_stats/rasterize/rasterize_feature_with_resolution.json, tests/test_stats/rasterize/rasterize_feature_with_shape.json
**WARNING:** if you review this before Monday I will draw an unflattering doodle of you. Do not play games with me!
Not sure if we should have a special case where we still try to load the parquet as a geoparquet. Seems kinda hard to do in general.
=> Support regular parquet in test statistics

eogrow/core/storage.py, tests/core/test_storage.py, tests/test_config_files/other/aws_storage_test.json
As discussed internally, this option is now removed in favor of always taking the value from the `AWS_PROFILE` environment variable.
=> Remove aws profile parameter from storage manager schema

eogrow/pipelines/download_batch.py, eogrow/utils/pipeline_chain.py
Issue is that SH has separate read/write databases which can be out of sync. Adds a wrapper for retrying on 404 around the GET request as well
Let me know if you want to name them differently
=> Fix bug with 404 on GET request for batch_request

.github/workflows/ci_action.yml, eogrow/utils/testing.py, pyproject.toml
In the `compare_content` we have the option to set the `save_new_stats` parameter to true, which will save the new statistics. The new statistics will then be compared and the comparison should find no difference, which is the only possible conclusion, since the comparison in this case is basically the identity check and brings no value.
It makes more sense to fail the test regardless of the `save_new_stats` parameter:
- such a behavior is more in line with pre-commit/lint checks, where fixes are applied, but the job fails if changes were made
- jobs can be run only once and you can then make use of the test as well as the stats update using artifacts
=> Fail stats comparison if changes are present also when updating the stats
